version: '3'
services:
  web:
    build: .
    ports:
      - "${VITE_API_PORT}:3000"
    environment:
      - VITE_API_URI=${VITE_API_URI}
    env_file:
      - .env
    volumes:
      - ./:/user/src/app
    command: npm run preview
  
networks:
  armc-web-network:
    driver: bridge